name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR Repository (if not exists)
        run: |
          aws ecr describe-repositories --repository-names patient-service || \
          aws ecr create-repository --repository-name patient-service

        run: |
          aws ecr describe-repositories --repository-names appointment-service || \
          aws ecr create-repository --repository-name appointment-service          
          

      - name: Build Docker Image (Patient)
        working-directory: app
        run: |
          echo "Building patient image..."
          docker build -t patient-service -f Dockerfile.patient .

      - name: Tag and Push Docker Image (Patient)
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/patient-service:latest
          docker tag patient-service:latest $IMAGE_URI
          docker push $IMAGE_URI
          
      - name: Build Docker Image (Appointment)
        working-directory: app
        run: |
          echo "Building appointment image..."
          docker build -t appointment-service -f Dockerfile.appointment .

      - name: Tag and Push Docker Image (Appointment)
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/appointment-service:latest
          docker tag appointment-service:latest $IMAGE_URI
          docker push $IMAGE_URI          
